[package]
name = "cccplayer-core"
version.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true
regex.workspace = true
chrono.workspace = true
sha2.workspace = true
hex.workspace = true
fs2.workspace = true
tempfile.workspace = true
zstd.workspace = true
tar.workspace = true
walkdir.workspace = true
futures.workspace = true
once_cell.workspace = true

[dev-dependencies]
tempfile.workspace = true
